#!/usr/bin/env bash
source bashlib

basedir=${0%/*}/../../../
[[ $basedir = /* ]] || basedir=$PWD/$basedir

host=gorillas.lhunath.com
jetty_path=/usr/local/share/jetty

war=("$basedir/target/"*.war)
rsync --bwlimit=20 -vP -p --chmod=ugo=rX "$war" "$host:$jetty_path/webapps/" && \
ssh "$host" "$(printf 'touch "$(grep -lF %q %q/contexts/*.xml)"' "${war##*/}" "$jetty_path")"
