#!/usr/bin/env bash
source bashlib

basedir=${0%/*}/../../../
[[ $basedir = /* ]] || basedir=$PWD/$basedir

host=satura.lyndir.com
jetty_path=/usr/local/share/jetty

emit "Deploying web application" --
    war=("$basedir/target/"*.war)
    rsync -p --chmod=ugo=rX "$war" "$host:$jetty_path/webapps/" && \
    ssh "$host" "$(printf 'touch "$(grep -lF %q %q/contexts/*.xml)"' "${war##*/}" "$jetty_path")"
emit -$?
